/**
 * PDF Export Utility for Analytics
 * 
 * Generate PDF reports from dashboard data
 * 
 * Features:
 * - Export any dashboard to PDF
 * - Include charts as images
 * - Tables with styling
 * - Header with logo and date
 * - Page numbering
 * - Custom branding
 * 
 * Usage:
 * ```typescript
 * await exportDashboardToPDF({
 *   dashboard: 'executive',
 *   data: dashboardData,
 *   filename: 'executive-report-2025-01.pdf'
 * })
 * ```
 */

import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { format } from 'date-fns'

export interface PDFExportOptions {
  dashboard: string
  title: string
  data: any
  filename: string
  includeLogo?: boolean
  includeCharts?: boolean
  customBranding?: {
    primaryColor: string
    companyName: string
    logoUrl?: string
  }
}

/**
 * Export dashboard to PDF
 */
export async function exportDashboardToPDF(options: PDFExportOptions) {
  const {
    dashboard,
    title,
    data,
    filename,
    includeLogo = true,
    includeCharts = false,
    customBranding,
  } = options
  
  // Create PDF document
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })
  
  // Settings
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20
  let yPosition = margin
  
  // Brand color
  const primaryColor = customBranding?.primaryColor || '#667eea'
  const rgb = hexToRgb(primaryColor)
  
  // Add header
  doc.setFillColor(rgb.r, rgb.g, rgb.b)
  doc.rect(0, 0, pageWidth, 30, 'F')
  
  // Title
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text(title, margin, 20)
  
  // Date
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  const dateStr = format(new Date(), 'MMMM d, yyyy')
  doc.text(dateStr, pageWidth - margin, 20, { align: 'right' })
  
  yPosition = 40
  
  // Company name
  if (customBranding?.companyName) {
    doc.setTextColor(100, 100, 100)
    doc.setFontSize(12)
    doc.text(customBranding.companyName, margin, yPosition)
    yPosition += 10
  }
  
  // Reset text color
  doc.setTextColor(0, 0, 0)
  
  // Add content based on dashboard type
  if (dashboard === 'executive') {
    yPosition = addExecutiveDashboardContent(doc, data, yPosition, margin, pageWidth)
  } else if (dashboard === 'crm') {
    yPosition = addCRMDashboardContent(doc, data, yPosition, margin, pageWidth)
  } else if (dashboard === 'marketing') {
    yPosition = addMarketingDashboardContent(doc, data, yPosition, margin, pageWidth)
  }
  
  // Add footer with page numbers
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    )
    doc.text(
      `Generated by Dental CRM Analytics`,
      margin,
      pageHeight - 10
    )
  }
  
  // Save PDF
  doc.save(filename)
  
  return {
    success: true,
    filename,
    pages: pageCount,
  }
}

/**
 * Add Executive Dashboard content
 */
function addExecutiveDashboardContent(
  doc: jsPDF,
  data: any,
  yPosition: number,
  margin: number,
  pageWidth: number
): number {
  // KPIs Section
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Key Performance Indicators', margin, yPosition)
  yPosition += 10
  
  // KPI table
  const kpiData = [
    ['Revenue', formatCurrency(data.revenue || 0)],
    ['Pipeline Value', formatCurrency(data.pipelineValue || 0)],
    ['Total Contacts', (data.contacts || 0).toLocaleString()],
    ['Win Rate', `${(data.winRate || 0).toFixed(1)}%`],
  ]
  
  autoTable(doc, {
    startY: yPosition,
    head: [['Metric', 'Value']],
    body: kpiData,
    theme: 'grid',
    headStyles: { fillColor: [102, 126, 234] },
    margin: { left: margin, right: margin },
  })
  
  yPosition = (doc as any).lastAutoTable.finalY + 15
  
  // Lead Sources Section
  if (data.leadSources && data.leadSources.length > 0) {
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('Lead Source Performance', margin, yPosition)
    yPosition += 10
    
    const leadSourceData = data.leadSources.map((source: any) => [
      source.name,
      source.contacts,
      source.deals,
      formatCurrency(source.revenue),
      `${source.conversionRate}%`,
    ])
    
    autoTable(doc, {
      startY: yPosition,
      head: [['Source', 'Contacts', 'Deals', 'Revenue', 'Conv. Rate']],
      body: leadSourceData,
      theme: 'striped',
      headStyles: { fillColor: [102, 126, 234] },
      margin: { left: margin, right: margin },
    })
    
    yPosition = (doc as any).lastAutoTable.finalY + 15
  }
  
  return yPosition
}

/**
 * Add CRM Dashboard content
 */
function addCRMDashboardContent(
  doc: jsPDF,
  data: any,
  yPosition: number,
  margin: number,
  pageWidth: number
): number {
  // Sales Performance Section
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Sales Team Performance', margin, yPosition)
  yPosition += 10
  
  if (data.salesReps && data.salesReps.length > 0) {
    const salesData = data.salesReps.map((rep: any) => [
      rep.name,
      rep.deals,
      rep.dealsWon,
      `${rep.winRate}%`,
      formatCurrency(rep.revenue),
    ])
    
    autoTable(doc, {
      startY: yPosition,
      head: [['Sales Rep', 'Total Deals', 'Won', 'Win Rate', 'Revenue']],
      body: salesData,
      theme: 'grid',
      headStyles: { fillColor: [102, 126, 234] },
      margin: { left: margin, right: margin },
    })
    
    yPosition = (doc as any).lastAutoTable.finalY + 15
  }
  
  return yPosition
}

/**
 * Add Marketing Dashboard content
 */
function addMarketingDashboardContent(
  doc: jsPDF,
  data: any,
  yPosition: number,
  margin: number,
  pageWidth: number
): number {
  // Marketing Metrics Section
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Marketing Performance', margin, yPosition)
  yPosition += 10
  
  const marketingMetrics = [
    ['Total Spend', formatCurrency(data.totalSpend || 0)],
    ['Revenue Generated', formatCurrency(data.revenueGenerated || 0)],
    ['CAC', formatCurrency(data.cac || 0)],
    ['LTV', formatCurrency(data.ltv || 0)],
    ['LTV:CAC Ratio', `${data.ltvCacRatio || 0}:1`],
    ['Marketing ROI', `${(data.roi || 0).toFixed(0)}%`],
  ]
  
  autoTable(doc, {
    startY: yPosition,
    head: [['Metric', 'Value']],
    body: marketingMetrics,
    theme: 'grid',
    headStyles: { fillColor: [102, 126, 234] },
    margin: { left: margin, right: margin },
  })
  
  yPosition = (doc as any).lastAutoTable.finalY + 15
  
  // Campaign Performance
  if (data.campaigns && data.campaigns.length > 0) {
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('Top Campaigns', margin, yPosition)
    yPosition += 10
    
    const campaignData = data.campaigns.slice(0, 10).map((campaign: any) => [
      campaign.name,
      campaign.type,
      `${campaign.openRate}%`,
      `${campaign.clickRate}%`,
      campaign.conversions,
      formatCurrency(campaign.revenue),
    ])
    
    autoTable(doc, {
      startY: yPosition,
      head: [['Campaign', 'Type', 'Open Rate', 'Click Rate', 'Conv.', 'Revenue']],
      body: campaignData,
      theme: 'striped',
      headStyles: { fillColor: [102, 126, 234] },
      margin: { left: margin, right: margin },
      styles: { fontSize: 8 },
    })
    
    yPosition = (doc as any).lastAutoTable.finalY + 15
  }
  
  return yPosition
}

/**
 * Helper: Convert hex color to RGB
 */
function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex)
  return result
    ? {
        r: parseInt(result[1], 16),
        g: parseInt(result[2], 16),
        b: parseInt(result[3], 16),
      }
    : { r: 102, g: 126, b: 234 }
}

/**
 * Helper: Format currency
 */
function formatCurrency(cents: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0,
  }).format(cents / 100)
}

/**
 * Export simple data table to PDF
 */
export async function exportTableToPDF(
  title: string,
  headers: string[],
  rows: any[][],
  filename: string
) {
  const doc = new jsPDF()
  
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text(title, 20, 20)
  
  doc.setFontSize(10)
  doc.text(format(new Date(), 'MMMM d, yyyy'), 20, 28)
  
  autoTable(doc, {
    startY: 35,
    head: [headers],
    body: rows,
    theme: 'grid',
    headStyles: { fillColor: [102, 126, 234] },
  })
  
  doc.save(filename)
}

