-- Quick fix for RLS and missing columns
-- Copy and paste this into your Supabase SQL Editor

-- Add missing columns to files table
ALTER TABLE files ADD COLUMN IF NOT EXISTS file_name TEXT;
ALTER TABLE files ADD COLUMN IF NOT EXISTS original_name TEXT;

-- Disable RLS on all tables for development
ALTER TABLE files DISABLE ROW LEVEL SECURITY;
ALTER TABLE activity_files DISABLE ROW LEVEL SECURITY;
ALTER TABLE ai_artifacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE tenants DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE pipelines DISABLE ROW LEVEL SECURITY;
ALTER TABLE pipeline_stages DISABLE ROW LEVEL SECURITY;
ALTER TABLE deals DISABLE ROW LEVEL SECURITY;
ALTER TABLE tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE audits DISABLE ROW LEVEL SECURITY;

